language: python
python: 3.7
dist: xenial
sudo: true
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install coveralls
before_script:
  - bash lint.sh
script:
  - bash test.sh
after_success:
  coveralls
